# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_MANAGER, ROLE_OPERATOR]
        ROLE_MANAGER: ROLE_OPERATOR

    encoders:
        BugTrackerBundle\Entity\User:
            algorithm: bcrypt
    providers:
        db_user:
            entity:
                class: BugTrackerBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        data_fixtures:
            pattern: ^/fixture
            security: false
        login_firewall:
            anonymous: ~
            pattern: ^/user/(login|register)$
        secured_area:
            form_login:
                login_path: login
                check_path: loginPost
            logout:
                path: logout
                target: /
            provider: db_user
