# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    bugtracker.issue_edit.form_type:
        class: BugTrackerBundle\Form\Issue\EditType
        arguments:
            ["@bugtracker.issue.helper"]
        tags:
            - { name: form.type}
    bugtracker.issue.helper:
        class: BugTrackerBundle\Helper\Issue
        public: true
    bugtracker.activity.mailer:
        class: BugTrackerBundle\Mailer\Activity
        arguments:
            ["@mailer", "@twig"]
        public: true
    bugtracker.user.form_handler:
        class: BugTrackerBundle\Form\Handler\UserHandler
        public: true
        arguments:
            ["@doctrine.orm.entity_manager", "@security.password_encoder", "@request_stack"]
    bugtracker.project.form_handler:
        class: BugTrackerBundle\Form\Handler\ProjectHandler
        public: true
        arguments:
            ["@doctrine.orm.entity_manager", "@request_stack"]
    bugtracker.issue.form_handler:
        class: BugTrackerBundle\Form\Handler\IssueHandler
        public: true
        arguments:
            ["@doctrine.orm.entity_manager", "@request_stack", "@bugtracker.issue.helper", "@bugtracker.activity.mailer"]
    bugtracker.activities.twig_extension:
        class: BugTrackerBundle\Twig\Activity
        public: false
        arguments:
            ["@doctrine.orm.entity_manager", "@request_stack"]
        tags:
            - { name: twig.extension }
    bugtracker.users.twig_extension:
        class: BugTrackerBundle\Twig\User
        public: false
        arguments:
            ["@doctrine.orm.entity_manager", "@request_stack"]
        tags:
            - { name: twig.extension }
    bugtracker.pagination.twig_extension:
        class: BugTrackerBundle\Twig\Pagination
        public: false
        arguments:
            ["@request_stack", "@router"]
        tags:
            - { name: twig.extension }
    bugtracker.project_voter:
        class: BugTrackerBundle\Security\ProjectVoter
        arguments:
            ["@doctrine.orm.entity_manager", "@security.access.decision_manager"]
        tags:
            - { name: security.voter }
        public: false
    bugtracker.issue_voter:
        class: BugTrackerBundle\Security\IssueVoter
        arguments:
            ["@doctrine.orm.entity_manager", "@security.access.decision_manager"]
        tags:
            - { name: security.voter }
        public: false
    bugtracker.user_voter:
        class: BugTrackerBundle\Security\UserVoter
        arguments:
            ["@security.access.decision_manager"]
        tags:
            - { name: security.voter }
        public: false
    bugtracker.comment_voter:
        class: BugTrackerBundle\Security\CommentVoter
        arguments:
            ["@security.access.decision_manager"]
        tags:
            - { name: security.voter }
        public: false
    bugtracker.contains_issue_type_validator:
            class: BugTrackerBundle\Validator\Constraints\Issue\TypeValidator
            arguments:
                ["@doctrine.orm.entity_manager", "@bugtracker.issue.helper"]
            tags:
                - { name: validator.constraint_validator }
    bugtracker.contains_issue_status_validator:
            class: BugTrackerBundle\Validator\Constraints\Issue\StatusValidator
            arguments:
                ["@doctrine.orm.entity_manager", "@bugtracker.issue.helper"]
            tags:
                - { name: validator.constraint_validator }
